use master
go


drop database GYMFUNLIMON
GO



sp_addlogin 'Diana','1234','GYMFUNLIMON'
-- Role
sp_addsrvrolemember 'Diana',sysadmin



Drop database if exists GYMFUNLIMON
go

CREATE DATABASE GYMFUNLIMON
GO

USE GYMFUNLIMON
GO


DROP TABLE IF EXISTS PERSONA
GO

CREATE TABLE Persona(
	ID_PERSONA TINYINT IDENTITY(1,1) not null,
	NOMBRE VARCHAR(30) not null,
	APELLIDO VARCHAR(30)not null,
	TELEFONO CHAR(8) CHECK(TELEFONO LIKE '[2|5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
	DIRECCION VARCHAR(281)
	CONSTRAINT PK_ID_PERSONA PRIMARY KEY (ID_PERSONA)
)
GO



DROP TABLE IF EXISTS USUARIO
GO

CREATE TABLE usuario (
	ID_USUARIO INT IDENTITY (1,1),
	USUARIO VARCHAR (40) NOT NULL,
	CONTRASEÑA VARBINARY (40) NOT NULL,
	TIPO_ROL VARCHAR (40) NOT NULL,
	ID_PERSONA TINYINT,
	CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO),
	CONSTRAINT FK_ID_PERSONA_U FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA)
)
GO


DROP TABLE IF EXISTS CLIENTE
GO

CREATE TABLE CLIENTE (
	ID_CLIENTE TINYINT IDENTITY (1,1),
	ID_PERSONA TINYINT
	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT FK_ID_PERSONA_C FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA)
)
GO


DROP TABLE IF EXISTS SERVICIOS
GO

CREATE TABLE SERVICIOS(
	CODIGO TINYINT IDENTITY(1,1) NOT NULL,
	DESCRIPCION Varchar (20),
	PRECIO DECIMAL(6,2) NOT NULL,
	
	CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO),
	
)
GO


DROP TABLE IF EXISTS PAGOS
GO

CREATE TABLE PAGOS(
	ID_PAGO TINYINT IDENTITY(1,1) NOT NULL,
	FECHA DATETIME DEFAULT GETDATE () NOT NULL,
	ID_CLIENTE TINYINT,
	TOTAL DECIMAL(6,2)

	PRIMARY KEY (ID_PAGO)
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
)
GO


DROP TABLE IF EXISTS DETALLEPAGOS 
GO
CREATE TABLE DETALLEPAGOS(
	ID_PAGO TINYINT FOREIGN KEY REFERENCES PAGOS (ID_PAGO) NOT NULL,
	CODIGO TINYINT  FOREIGN KEY REFERENCES SERVICIOS (CODIGO) NOT NULL,
	CANTV INT NOT NULL,
	SUBTV DECIMAL (6,2),

	PRIMARY KEY(ID_PAGO,CODIGO)
)
GO
